"""Generate the K x alpha grid tables for Experiments A and B at one or
more encoder configurations, writing each set into its own .tex file.

Usage:
    python /tmp/gen_ab_grids.py
    python /tmp/gen_ab_grids.py --encoder-a dinov2-large --encoder-b mert-330m

Default behaviour emits all four configurations the user has on disk:
    (clip-large, MiniLM)        -> results/tables_ab_grids.tex          (existing)
    (dinov2-large, MiniLM)      -> results/tables_ab_grids__dino.tex    (new)
    (clap-unfused, MiniLM)      -> covered by the first file
    (mert-330m, MiniLM)         -> results/tables_ab_grids__mert.tex    (new)
"""
import argparse
import sys
from pathlib import Path
import pandas as pd

ROOT = Path("/home/lucio/av-bridge")
RES = ROOT / "results"


def emit(path, exp_letter, scope, label_suffix, exp_title, K_cl, caption_extras=""):
    if not path.exists():
        return None
    df = pd.read_csv(path)
    sub = df[df.scope == scope]
    if sub.empty:
        return None
    Ks = sorted(sub.K.unique())
    alphas = sorted(sub.alpha.unique())
    n_alpha = len(alphas)
    scope_word = "aggregate" if scope == "aggregate" else "held-out"
    scope_tag = "agg" if scope == "aggregate" else "hel"

    lines = [
        r"\begin{table}[!ht]",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{l " + " ".join(["ccc"] * n_alpha) + r"}",
        r"\toprule",
    ]
    top = "      "
    for a in alphas:
        top += f" & \\multicolumn{{3}}{{c}}{{$\\alpha = {a:.1f}$}}"
    lines.append(top + r" \\")
    rule_parts = []
    for i in range(n_alpha):
        lo = 2 + 3 * i
        hi = lo + 2
        rule_parts.append(f"\\cmidrule(lr){{{lo}-{hi}}}")
    lines.append("        " + " ".join(rule_parts))
    metric_hdr = "$K$"
    for _ in alphas:
        metric_hdr += " & $R@10$ & NMI & $r$"
    lines.append(metric_hdr + r" \\")
    lines.append(r"\midrule")
    for K in Ks:
        row_cells = [str(K)]
        for a in alphas:
            r = sub[(sub.K == K) & (sub.alpha == a)]
            if r.empty:
                row_cells.extend([r"\textemdash"] * 3)
                continue
            r = r.iloc[0]
            if pd.isna(r["R@10"]):
                row_cells.extend([r"\textemdash"] * 3)
            else:
                row_cells.extend([
                    f"{r['R@10']:.3f}",
                    f"{r['nmi']:.3f}",
                    f"{r['pearson_r']:.3f}",
                ])
        lines.append(" & ".join(row_cells) + r" \\")
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    cap = (
        f"Experiment~{exp_title}: $K \\times \\alpha$ grid at "
        f"\\textbf{{{scope_word}}} scope ($n = 400$). For each "
        f"$(K, \\alpha)$ cell we report $R@10$, NMI (uncorrected), and "
        f"Pearson $r$; $K_{{\\mathrm{{cl}}}} = {K_cl}$ for the NMI "
        f"computation. {caption_extras}"
    )
    lines.append(f"\\caption{{{cap}}}")
    lines.append(f"\\label{{tab:{exp_letter}{label_suffix}-grid-{scope_tag}}}")
    lines.append(r"\end{table}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exp-a-csv", default=str(RES / "exp_a__dinov2-large" / "sweep.csv"))
    ap.add_argument("--exp-b-csv", default=str(RES / "exp_b__mert-330m" / "sweep.csv"))
    ap.add_argument("--out-a", default=str(RES / "tables_ab_grids__dino.tex"))
    ap.add_argument("--out-b", default=str(RES / "tables_ab_grids__mert.tex"))
    ap.add_argument("--encoder-a-name", default="DINOv2-large")
    ap.add_argument("--encoder-b-name", default="MERT-330m")
    args = ap.parse_args()

    HEADER = (
        "% =====================================================================\n"
        "% K x alpha grids: R@10 / NMI / Pearson r per (K, alpha) cell\n"
        "% Generated by /tmp/gen_ab_grids.py\n"
        "% Requires: booktabs, graphicx (for \\resizebox).\n"
        "% =====================================================================\n"
    )

    a_path = Path(args.exp_a_csv)
    if a_path.exists():
        chunks = [HEADER]
        chunks.append(emit(a_path, "a", "aggregate", "-dino", f"A --- image $\\to$ visual-caption text ({args.encoder_a_name} $\\times$ MiniLM)", 10) or "")
        chunks.append(emit(a_path, "a", "heldout",   "-dino", f"A --- image $\\to$ visual-caption text ({args.encoder_a_name} $\\times$ MiniLM)", 10,
                           caption_extras="The $K = 400$ row has no held-out partition by construction.") or "")
        Path(args.out_a).write_text("\n".join(chunks))
        print(f"[A] wrote {args.out_a}")
    else:
        print(f"[A] skip: {a_path} not present. Re-run "
              f"`python code/run_experiments.py --exp a --image-encoder {a_path.parent.name.split('__')[-1]}` on HPC.")

    b_path = Path(args.exp_b_csv)
    if b_path.exists():
        chunks = [HEADER]
        chunks.append(emit(b_path, "b", "aggregate", "-mert", f"B --- audio $\\to$ audio-caption text ({args.encoder_b_name} $\\times$ MiniLM)", 20) or "")
        chunks.append(emit(b_path, "b", "heldout",   "-mert", f"B --- audio $\\to$ audio-caption text ({args.encoder_b_name} $\\times$ MiniLM)", 20,
                           caption_extras="The $K = 400$ row has no held-out partition by construction.") or "")
        Path(args.out_b).write_text("\n".join(chunks))
        print(f"[B] wrote {args.out_b}")
    else:
        print(f"[B] skip: {b_path} not present. Re-run "
              f"`python code/run_experiments.py --exp b --audio-encoder {b_path.parent.name.split('__')[-1]}` on HPC.")


if __name__ == "__main__":
    main()
